config/routes.rb
Colchonet::Application.routes.draw do

	LOCALES = /en|pt\-BR/

	scope "(:locale)", locale: LOCALES do
		resources :rooms do
			resources :reviews, only: [:create, :update], module: :rooms
		end
		resources :users

		resource :confirmation, only: [:show]
		resource :user_sessions, only: [:create, :new, :destroy]
	end

	get '/:locale' => 'home#index', locale: LOCALES
	root 'home#index'

  

end

app/models/room.rb
class Room < ActiveRecord::Base
	extend FriendlyId

	has_many :reviews, dependent: :destroy
	belongs_to :user

	validates_presence_of :title, :location, :slug
	validates_length_of :description, minimun: 30, allow_blank: false
	mount_uploader :picture, PictureUploader
	friendly_id :title, use: [:slugged, :history]

	def complete_name
		"#{title}, #{location}"
	end

	# se confirmed_at esta nil, o email de confirmacao ainda nao foi feito
	scope :confirmed, -> {where.not(confirmed_at: nil)}

	# dos mais antigos aos mais recentes
	scope :most_recent, -> {all.reverse}

	def self.search(query)
		if query.present?
			#postgre sql
			where(['location ILIKE :query OR title ILIKE :query OR description ILIKE :query', query: "%#{query}%"])

			#mysql
			#where(['location LIKE :query OR title LIKE :query OR description LIKE :query', query: "%#{query}%"])

		#se não tem resultado da busca, continua com o resultado antigo
		else
			scoped
		end
	end


end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController

	before_filter :require_authentication

	def create
		review = room.reviews.find_or_initialize_by(current_user.id)
		review.update(review_params)
		head :ok
	end

	def update
		create
	end


	private

	def room
		@room ||= Room.find(params[:room_id])
	end

	def review_params
		params.
				require(:review).permit(:points)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	PER_PAGE = 10
	delegate :current_page, :num_pages, :limit_value, :total_pages, to: :@rooms
	before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

	#def index
	#	@search_query = params[:q]
	#
	#	rooms = Room.search(@search_query).
	#			page(params[:page]).
	#			per(PER_PAGE)
	#
	#	@rooms = RoomCollectionPresenter.new(rooms.most_recent, self)
	#end

	def index
		@search_query = params[:q]
		rooms = Room.search(@search_query).page(params[:page]).per(PER_PAGE)

		@rooms = RoomCollectionPresenter.new(rooms.most_recent, self)
	end

	def show
		room_model = Room.friendly.find(params[:id])
		@room = RoomPresenter.new(room_model, self)
	end

	def new
		@room = current_user.rooms.build
	end

	def edit
		@room = current_user.rooms.friendly.find(params[:id])
	end

	def create
		@room = current_user.rooms.build(room_params)

		if @room.save
			redirect_to @room, notice: t('flash.notice.room_created')
		else
			render action: "new"
		end
	end

	def update
		@room = current_user.rooms.friendly.find(params[:id])

		if @room.update(room_params)
			redirect_to @room, notice: t('flash.notice.room_updated')
		else
			render action: "edit"
		end
	end

	def destroy
		@room = current_user.rooms.friendly.find(params[:id])
		@room.destroy
		redirect_to rooms_url
	end


	private

	def room_params
		params.
				require(:room).
				permit(:title, :location, :description, :picture)
	end

end

app/helpers/rooms_helper.rb
module RoomsHelper

	def belongs_to_user(room)
		user_signed_in? && room.user == current_user
	end

end

app/views/rooms/_form.html.erb
<% if @room.errors.any? %>
  <div id="error_explanation">
    <h2><%= t 'general.form_error' %> </h2>
  </div>
<% end %>

<%= form_for(@room) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
	  <%= error_tag @room, :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
	<p>
	  <%= f.label :picture %>
	  <%= f.file_field :picture %>
	  <%= error_tag @room, :picture %>
	</p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
    <% room.stars.times do %>
      <span class="star filled_star"></span>
    <% end %>
    <% (room.review_points.max - room.stars).times do %>
      <span class="star empty_star"></span>
    <% end %>
    <%= t '.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point %>
      <%= f.label :points, value: point do %>
        <i class="icon-star"></i>
      <% end %>
    <% end %>
    <%= f.submit %>
  <% end %>
<% else %>
  <span class="login_required">
	<%= t('.login_to_review') %> </span>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
  <%= link_to highlight(room.title, @search_query), room.route %>

  <%= render partial: 'review', locals: {room: room} %>

  <span class="created">
    <%= t '.owner_html',
          :owner => room.user.full_name,
          :when => l(room.created_at, :format => :short) %>
  </span>
  <p>
    <%= link_to highlight(room.location, @search_query),
                "https://maps.google.com/?q=#{room.location}",
                target: :blank %>
    </span>
  </p>
  <div class="room-description">
    <%= link_to( image_tag(room.thumb_url), room.picture_url ) if room.has_picture? %>
    <p><%= highlight(room.description || '', @search_query) %> </p>
  </div>


  <% if belongs_to_user(room) %>
    <ul>
      <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
      <li><%= link_to t('.destroy'), room_path(room.route), :method => :delete, :data => {:confirm => t('dialogs.destroy')} %></li>
    </ul>
  <% end %>

</article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query, placeholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>
<h1>
  <% if @search_query.present? %>
    <%= t '.search_results' %>
  <% else %>
    <%= t '.title' %>
  <% end %>
  <!--(<%#= @rooms.size %>)-->
</h1>

<%#= render @rooms, locals: {the_room: current_user.rooms.first} %>
<%= render @rooms %>

<%#= paginate @rooms %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Voltar', root_path %>

app/views/rooms/show.html.erb
<%= render @room %>
<%#= render partial: 'room', object: @room %>
<%#= render partial: 'room', object: current_user.rooms.first %>

<!--
<p id="notice"><%= notice %></p>